version: '3'
services:
  php:
    build:
      context: docker/php-fpm
    restart: always
    volumes:
      - ./app:/var/www/html

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
      - db

  db:
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./docker/storage/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 0
    ports:
      - "8080:80"